export const POSTAVI_ALERT = "POSTAVI_ALERT";
export const IZBRISI_ALERT = "IZBRISI_ALERT";
export const REGISTRACIJA_NEUSPESNA = "REGISTRACIJA_NEUSPESNA";
export const REGISTRACIJA_USPESNA = "REGISTRACIJA_USPESNA";
export const KORISNIK_UCITAN = "KORISNIK_UCITAN";
export const GRESKA_U_AUTORIZACIJI = "GRESKA_U_AUTORIZACIJI";
export const USPESNO_LOGOVANJE = "USPESNO_LOGOVANJE";
export const NEUSPESNO_LOGOVANJE = "NEUSPESNO_LOGOVANJE";
export const LOGOUT = "LOGOUT";

export const UZMI_PROFIL = "UZMI_PROFIL";
export const UZMI_PROFILE = "UZMI_PROFILE";
export const AZURIRAJ_PROFIL = "AZURIRAJ_PROFIL";
export const PROFIL_GRESKA = "PROFIL_GRESKA";
export const OCISTI_PROFIL = "OCISTI_PROFIL";
export const OBRISI_NALOG = "OBRISI_NALOG";

export const UZMI_POST = "UZMI_POST";
export const UZMI_POSTOVE = "UZMI_POSTOVE";
export const POST_GRESKA = "POST_GRESKA";
export const AZURIRAJ_LAJK = "AZURIRAJ_LAJK";
export const OBRISI_POST = "OBRISI_POST";
export const DODAJ_POST = "DODAJ_POST";
export const DODAJ_KOMENTAR = "DODAJ_KOMENTAR";
export const OBRISI_KOMENTAR = "OBRISI_KOMENTAR";
